### ISSUE TITLE
RxJS v7 compatibility

### ISSUE THREAD

**Issue by rassie** [cartant/rxjs-spy#58]
After upgrading my code base to v7, I get quite a lot of errors from `rxjs-spy`, mostly about `TypeError: this.destination.next is not a function` (with rather weird line number offset, which points to `this.destination.complete`, rather than `.next`). However, this error does not prevent `rxjs-spy` from running completely, since I see output in the console, but it's still preventing the app from working.

I thought I could run `rxjs-spy`'s tests with RxJS 7 to verify that the problem is with `rxjs-spy`. For that I've bumped TypeScript and RxJS dependency and have got at least four compilation errors, which I could not fix ad hoc.

Is v7 compatibility planned for `rxjs-spy` planned? If not, how are rxjs.tools coming along? :)

**Comment by cartant** [comment]
Getting it working with version 7 should not be too hard. The breaking changes are limited to the `Subscriber` ctor, IIRC. I'll take a peek at it.

**Comment by rassie** [comment]
Thanks! This was quick :)
